commands:
    - command:
        name: start minecraft
        script: startMinecraft.sh
    - command:
        name: test
        script: script.sh
listen_channels:
    - "channelID"
    - "channelID"
